# Generated by Django 3.0.7 on 2020-06-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Playlist'),
        ),
    ]
